FROM node:26-alpine AS build
WORKDIR /app
COPY ts ts
COPY chunks chunks

WORKDIR /app/ts
RUN npm i

WORKDIR /app/ts/packages/build
RUN npm run generate

WORKDIR /app/ts/packages/space-dsl
RUN npm run build

WORKDIR /app/ts/packages/react-client
RUN npm run build

CMD ["npx", "http-server", "dist/", "--port", "1234"]
