// Generated by the C# M2TypesGenerator: modify at your own risk!
// ReSharper disable InconsistentNaming
// ReSharper disable SuggestVarOrType_SimpleTypes
// ReSharper disable SuggestVarOrType_Elsewhere
#pragma warning disable 1591
#nullable enable
namespace Languages;
using global::LionWeb.Core;
using global::LionWeb.Core.M2;
using global::LionWeb.Core.M3;
using global::LionWeb.Core.Notification;
using global::LionWeb.Core.Notification.Partition;
using global::LionWeb.Core.Notification.Pipe;
using global::LionWeb.Core.Utilities;
using global::LionWeb.Core.VersionSpecific.V2023_1;
using global::System;
using global::System.Collections.Generic;
using global::System.Diagnostics.CodeAnalysis;

[LionCoreLanguage(Key = "space-PowerBudget", Version = "0.1")]
public partial class PowerBudgetLanguageLanguage : LanguageBase<IPowerBudgetLanguageFactory>
{
	public static readonly PowerBudgetLanguageLanguage Instance = new Lazy<PowerBudgetLanguageLanguage>(() => new("space-PowerBudget")).Value;
	public PowerBudgetLanguageLanguage(string id) : base(id, LionWebVersions.v2023_1)
	{
		_iPowerModuleContent = new(() => new InterfaceBase<PowerBudgetLanguageLanguage>("IPowerModuleContent", this) { Key = "IPowerModuleContent", Name = "IPowerModuleContent", ExtendsLazy = new(() => [_builtIns.INamed]) });
		_iPowerParticipant = new(() => new InterfaceBase<PowerBudgetLanguageLanguage>("IPowerParticipant", this) { Key = "IPowerParticipant", Name = "IPowerParticipant", FeaturesLazy = new(() => [IPowerParticipant_continuous, IPowerParticipant_peak]) });
		_iPowerParticipant_continuous = new(() => new PropertyBase<PowerBudgetLanguageLanguage>("IPowerParticipant-continuous", IPowerParticipant, this) { Key = "IPowerParticipant-continuous", Name = "continuous", Optional = true, Type = _builtIns.Integer });
		_iPowerParticipant_peak = new(() => new PropertyBase<PowerBudgetLanguageLanguage>("IPowerParticipant-peak", IPowerParticipant, this) { Key = "IPowerParticipant-peak", Name = "peak", Optional = true, Type = _builtIns.Integer });
		_powerConsumer = new(() => new ConceptBase<PowerBudgetLanguageLanguage>("PowerConsumer", this) { Key = "PowerConsumer", Name = "PowerConsumer", Abstract = false, Partition = false, ExtendsLazy = new(() => _builtIns.Node), ImplementsLazy = new(() => [IPowerModuleContent, IPowerParticipant]), FeaturesLazy = new(() => [PowerConsumer_providedFrom]) });
		_powerConsumer_providedFrom = new(() => new ReferenceBase<PowerBudgetLanguageLanguage>("ODgyNjBiZDctZjQ0MC00ZWNhLTk4NzMtMTJkOTRjYjZlNzQ3LzEwMDI1NjMxNTEwMTY3ODAxOTUvMTAwMjU2MzE1MTAxNjg4NTY0Nw", PowerConsumer, this) { Key = "ODgyNjBiZDctZjQ0MC00ZWNhLTk4NzMtMTJkOTRjYjZlNzQ3LzEwMDI1NjMxNTEwMTY3ODAxOTUvMTAwMjU2MzE1MTAxNjg4NTY0Nw", Name = "providedFrom", Optional = true, Multiple = true, Type = PowerSource });
		_powerModule = new(() => new ConceptBase<PowerBudgetLanguageLanguage>("PowerModule", this) { Key = "PowerModule", Name = "PowerModule", Abstract = false, Partition = true, ExtendsLazy = new(() => _builtIns.Node), ImplementsLazy = new(() => [_builtIns.INamed]), FeaturesLazy = new(() => [PowerModule_contents]) });
		_powerModule_contents = new(() => new ContainmentBase<PowerBudgetLanguageLanguage>("PowerModule-contents", PowerModule, this) { Key = "PowerModule-contents", Name = "contents", Optional = true, Multiple = true, Type = IPowerModuleContent });
		_powerSource = new(() => new ConceptBase<PowerBudgetLanguageLanguage>("PowerSource", this) { Key = "PowerSource", Name = "PowerSource", Abstract = false, Partition = false, ExtendsLazy = new(() => _builtIns.Node), ImplementsLazy = new(() => [IPowerModuleContent, IPowerParticipant]), FeaturesLazy = new(() => [PowerSource_kind]) });
		_powerSource_kind = new(() => new PropertyBase<PowerBudgetLanguageLanguage>("PowerSource-kind", PowerSource, this) { Key = "PowerSource-kind", Name = "kind", Optional = true, Type = PowerSourceKind });
		_powerSourceKind = new(() => new EnumerationBase<PowerBudgetLanguageLanguage>("PowerSourceKind", this) { Key = "PowerSourceKind", Name = "PowerSourceKind", LiteralsLazy = new(() => [PowerSourceKind_diesel, PowerSourceKind_nuclear, PowerSourceKind_solar]) });
		_powerSourceKind_diesel = new(() => new EnumerationLiteralBase<PowerBudgetLanguageLanguage>("PowerSourceKind-diesel", PowerSourceKind, this) { Key = "PowerSourceKind-diesel", Name = "diesel" });
		_powerSourceKind_nuclear = new(() => new EnumerationLiteralBase<PowerBudgetLanguageLanguage>("PowerSourceKind-nuclear", PowerSourceKind, this) { Key = "PowerSourceKind-nuclear", Name = "nuclear" });
		_powerSourceKind_solar = new(() => new EnumerationLiteralBase<PowerBudgetLanguageLanguage>("PowerSourceKind-solar", PowerSourceKind, this) { Key = "PowerSourceKind-solar", Name = "solar" });
		_factory = new PowerBudgetLanguageFactory(this);
	}

	/// <inheritdoc/>
        public override IReadOnlyList<LanguageEntity> Entities => [IPowerModuleContent, IPowerParticipant, PowerConsumer, PowerModule, PowerSource, PowerSourceKind];
	/// <inheritdoc/>
        public override IReadOnlyList<Language> DependsOn => [];

	private const string _key = "space-PowerBudget";
	/// <inheritdoc/>
        public override string Key => _key;

	private const string _name = "PowerBudgetLanguage";
	/// <inheritdoc/>
        public override string Name => _name;

	private const string _version = "0.1";
	/// <inheritdoc/>
        public override string Version => _version;

	private readonly Lazy<Interface> _iPowerModuleContent;
	public Interface IPowerModuleContent => _iPowerModuleContent.Value;

	private readonly Lazy<Interface> _iPowerParticipant;
	public Interface IPowerParticipant => _iPowerParticipant.Value;

	private readonly Lazy<Property> _iPowerParticipant_continuous;
	public Property IPowerParticipant_continuous => _iPowerParticipant_continuous.Value;

	private readonly Lazy<Property> _iPowerParticipant_peak;
	public Property IPowerParticipant_peak => _iPowerParticipant_peak.Value;

	private readonly Lazy<Concept> _powerConsumer;
	public Concept PowerConsumer => _powerConsumer.Value;

	private readonly Lazy<Reference> _powerConsumer_providedFrom;
	public Reference PowerConsumer_providedFrom => _powerConsumer_providedFrom.Value;

	private readonly Lazy<Concept> _powerModule;
	public Concept PowerModule => _powerModule.Value;

	private readonly Lazy<Containment> _powerModule_contents;
	public Containment PowerModule_contents => _powerModule_contents.Value;

	private readonly Lazy<Concept> _powerSource;
	public Concept PowerSource => _powerSource.Value;

	private readonly Lazy<Property> _powerSource_kind;
	public Property PowerSource_kind => _powerSource_kind.Value;

	private readonly Lazy<Enumeration> _powerSourceKind;
	public Enumeration PowerSourceKind => _powerSourceKind.Value;

	private readonly Lazy<EnumerationLiteral> _powerSourceKind_diesel;
	public EnumerationLiteral PowerSourceKind_diesel => _powerSourceKind_diesel.Value;

	private readonly Lazy<EnumerationLiteral> _powerSourceKind_nuclear;
	public EnumerationLiteral PowerSourceKind_nuclear => _powerSourceKind_nuclear.Value;

	private readonly Lazy<EnumerationLiteral> _powerSourceKind_solar;
	public EnumerationLiteral PowerSourceKind_solar => _powerSourceKind_solar.Value;
}

public partial interface IPowerBudgetLanguageFactory : INodeFactory
{
	public PowerConsumer NewPowerConsumer(string id);
	public PowerConsumer CreatePowerConsumer();
	public PowerModule NewPowerModule(string id);
	public PowerModule CreatePowerModule();
	public PowerSource NewPowerSource(string id);
	public PowerSource CreatePowerSource();
}

public class PowerBudgetLanguageFactory : AbstractBaseNodeFactory, IPowerBudgetLanguageFactory
{
	private readonly PowerBudgetLanguageLanguage _language;
	public PowerBudgetLanguageFactory(PowerBudgetLanguageLanguage language) : base(language)
	{
		_language = language;
	}

	/// <inheritdoc/>
        public override INode CreateNode(string id, Classifier classifier)
	{
		if (_language.PowerConsumer.EqualsIdentity(classifier))
			return NewPowerConsumer(id);
		if (_language.PowerModule.EqualsIdentity(classifier))
			return NewPowerModule(id);
		if (_language.PowerSource.EqualsIdentity(classifier))
			return NewPowerSource(id);
		throw new UnsupportedClassifierException(classifier);
	}

	/// <inheritdoc/>
        public override Enum GetEnumerationLiteral(EnumerationLiteral literal)
	{
		if (_language.PowerSourceKind.EqualsIdentity(literal.GetEnumeration()))
			return EnumValueFor<PowerSourceKind>(literal);
		throw new UnsupportedEnumerationLiteralException(literal);
	}

	/// <inheritdoc/>
        public override IStructuredDataTypeInstance CreateStructuredDataTypeInstance(StructuredDataType structuredDataType, IFieldValues fieldValues)
	{
		throw new UnsupportedStructuredDataTypeException(structuredDataType);
	}

	public virtual PowerConsumer NewPowerConsumer(string id) => new(id);
	public virtual PowerConsumer CreatePowerConsumer() => NewPowerConsumer(GetNewId());
	public virtual PowerModule NewPowerModule(string id) => new(id);
	public virtual PowerModule CreatePowerModule() => NewPowerModule(GetNewId());
	public virtual PowerSource NewPowerSource(string id) => new(id);
	public virtual PowerSource CreatePowerSource() => NewPowerSource(GetNewId());
}

[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "IPowerModuleContent")]
public partial interface IPowerModuleContent : INamedWritable, INode
{
}

[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "IPowerParticipant")]
public partial interface IPowerParticipant : INode
{
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "IPowerParticipant-continuous")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public int? Continuous { get; set; }

	/// <remarks>Optional Property</remarks>
        public IPowerParticipant SetContinuous(int? value);
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "IPowerParticipant-peak")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public int? Peak { get; set; }

	/// <remarks>Optional Property</remarks>
        public IPowerParticipant SetPeak(int? value);
}

[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerConsumer")]
public partial class PowerConsumer : ConceptInstanceBase, IPowerModuleContent, IPowerParticipant, INamedWritable
{
	private string? _name = null;
	private bool SetNameRaw(string? value)
	{
		if (value == _name)
			return false;
		_name = value;
		return true;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "UnsetFeatureException">If Name has not been set</exception>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        [LionCoreMetaPointer(Language = typeof(LionWeb.Core.VersionSpecific.V2023_1.BuiltInsLanguage_2023_1), Key = "LionCore-builtins-INamed-name")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
	public string Name { get => _name ?? throw new UnsetFeatureException(_builtIns.INamed_name); set => SetName(value); }

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public bool TryGetName([NotNullWhenAttribute(true)] out string? name)
	{
		name = _name;
		return name != null;
	}
/// <remarks>Required Property</remarks>
/// <exception cref="InvalidValueException">If set to null</exception>
 INamedWritable INamedWritable.SetName(string value) => SetName(value);
	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public PowerConsumer SetName(string value)
	{
		SetRequiredReferenceTypeProperty<string>(value, _builtIns.INamed_name, _name, SetNameRaw);
		return this;
	}

	private int? _continuous = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "IPowerParticipant-continuous")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public int? Continuous { get => _continuous; set => SetContinuous(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetContinuous([NotNullWhenAttribute(true)] out int? continuous)
	{
		continuous = _continuous;
		return continuous != null;
	}

	private bool SetContinuousRaw(int? value)
	{
		if (value == _continuous)
			return false;
		_continuous = value;
		return true;
	}
/// <remarks>Optional Property</remarks>
 IPowerParticipant IPowerParticipant.SetContinuous(int? value) => SetContinuous(value);
	/// <remarks>Optional Property</remarks>
        public PowerConsumer SetContinuous(int? value)
	{
		SetOptionalValueTypeProperty<int>(value, PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous, _continuous, SetContinuousRaw);
		return this;
	}

	private int? _peak = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "IPowerParticipant-peak")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public int? Peak { get => _peak; set => SetPeak(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetPeak([NotNullWhenAttribute(true)] out int? peak)
	{
		peak = _peak;
		return peak != null;
	}

	private bool SetPeakRaw(int? value)
	{
		if (value == _peak)
			return false;
		_peak = value;
		return true;
	}
/// <remarks>Optional Property</remarks>
 IPowerParticipant IPowerParticipant.SetPeak(int? value) => SetPeak(value);
	/// <remarks>Optional Property</remarks>
        public PowerConsumer SetPeak(int? value)
	{
		SetOptionalValueTypeProperty<int>(value, PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak, _peak, SetPeakRaw);
		return this;
	}

	private List<ReferenceTarget>? _providedFrom;
	private IReadOnlyList<ReferenceTarget> ReadOnlyProvidedFrom() => _providedFrom?.AsReadOnly() ?? _emptyReferences;
	private List<ReferenceTarget> WritableProvidedFrom() => _providedFrom ??= [];
	/// <remarks>Optional Multiple Reference</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "ODgyNjBiZDctZjQ0MC00ZWNhLTk4NzMtMTJkOTRjYjZlNzQ3LzEwMDI1NjMxNTEwMTY3ODAxOTUvMTAwMjU2MzE1MTAxNjg4NTY0Nw")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Reference, Optional = true, Multiple = true)]
	public IReadOnlyList<PowerSource> ProvidedFrom { get => ReferenceTargetNonNullTargets<PowerSource>(_providedFrom, PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom); init => AddProvidedFrom(value); }

	/// <remarks>Optional Multiple Reference</remarks>
        public bool TryGetProvidedFrom([NotNullWhenAttribute(true)] out IReadOnlyList<PowerSource> providedFrom) => TryGetReference<PowerSource>(_providedFrom, out providedFrom);
	private bool SetProvidedFromRaw(List<ReferenceTarget> targets) => SetReferencesRaw(targets, WritableProvidedFrom());
	private bool AddProvidedFromRaw(ReferenceTarget target) => AddReferencesRaw(target, WritableProvidedFrom());
	private bool InsertProvidedFromRaw(int index, ReferenceTarget target) => InsertReferencesRaw(index, target, WritableProvidedFrom());
	private bool RemoveProvidedFromRaw(ReferenceTarget target) => RemoveReferencesRaw(target, _providedFrom);
	/// <remarks>Optional Multiple Reference</remarks>
        public PowerConsumer AddProvidedFrom(IEnumerable<PowerSource> nodes)
	{
		AddOptionalMultipleReference<PowerSource>(nodes, PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom, WritableProvidedFrom(), AddProvidedFromRaw);
		return this;
	}

	/// <remarks>Optional Multiple Reference</remarks>
        public PowerConsumer InsertProvidedFrom(int index, IEnumerable<PowerSource> nodes)
	{
		InsertOptionalMultipleReference<PowerSource>(index, nodes, PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom, WritableProvidedFrom(), InsertProvidedFromRaw);
		return this;
	}

	/// <remarks>Optional Multiple Reference</remarks>
        public PowerConsumer RemoveProvidedFrom(IEnumerable<PowerSource> nodes)
	{
		RemoveOptionalMultipleReference<PowerSource>(nodes, PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom, _providedFrom, RemoveProvidedFromRaw);
		return this;
	}

	public PowerConsumer(string id) : base(id)
	{
	}

	/// <inheritdoc/>
        public override Concept GetConcept() => PowerBudgetLanguageLanguage.Instance.PowerConsumer;
	/// <inheritdoc/>
        protected override bool GetInternal(Feature? feature, out object? result)
	{
		if (base.GetInternal(feature, out result))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			result = Name;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous.EqualsIdentity(feature))
		{
			result = Continuous;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak.EqualsIdentity(feature))
		{
			result = Peak;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(feature))
		{
			result = ProvidedFrom;
			return true;
		}

		return false;
	}

	protected override bool TryGetPropertyRaw(Property feature, out object? result)
	{
		if (base.TryGetPropertyRaw(feature, out result))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			result = _name;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous.EqualsIdentity(feature))
		{
			result = _continuous;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak.EqualsIdentity(feature))
		{
			result = _peak;
			return true;
		}

		return false;
	}

	protected override bool TryGetReferencesRaw(Reference feature, out IReadOnlyList<IReferenceTarget> result)
	{
		if (base.TryGetReferencesRaw(feature, out result))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(feature))
		{
			result = ReadOnlyProvidedFrom();
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool SetInternal(Feature? feature, object? value)
	{
		if (base.SetInternal(feature, value))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			if (value is string v)
			{
				SetName(v);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous.EqualsIdentity(feature))
		{
			if (value is null or int)
			{
				SetContinuous((int?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak.EqualsIdentity(feature))
		{
			if (value is null or int)
			{
				SetPeak((int?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(feature))
		{
			SetOptionalMultipleReference<PowerSource>(value, PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom, WritableProvidedFrom(), SetProvidedFromRaw);
			return true;
		}

		return false;
	}

	protected override bool SetPropertyRaw(Property feature, object? value)
	{
		if (base.SetPropertyRaw(feature, value))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature) && value is null or string)
			return SetNameRaw((string?)value);
		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous.EqualsIdentity(feature) && value is null or int)
			return SetContinuousRaw((int?)value);
		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak.EqualsIdentity(feature) && value is null or int)
			return SetPeakRaw((int?)value);
		return false;
	}

	/// <inheritdoc/>
        public override IEnumerable<Feature> CollectAllSetFeatures()
	{
		List<Feature> result = base.CollectAllSetFeatures().ToList();
		if (TryGetName(out _))
			result.Add(_builtIns.INamed_name);
		if (TryGetContinuous(out _))
			result.Add(PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous);
		if (TryGetPeak(out _))
			result.Add(PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak);
		if (TryGetProvidedFrom(out _))
			result.Add(PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom);
		return result;
	}

	protected override bool AddReferencesRaw(Reference feature, ReferenceTarget value)
	{
		if (base.AddReferencesRaw(feature, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(feature))
			return AddProvidedFromRaw(value);
		return false;
	}

	protected override bool InsertReferencesRaw(Reference feature, int index, ReferenceTarget value)
	{
		if (base.InsertReferencesRaw(feature, index, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(feature))
			return InsertProvidedFromRaw(index, value);
		return false;
	}

	protected override bool RemoveReferencesRaw(Reference feature, ReferenceTarget value)
	{
		if (base.RemoveReferencesRaw(feature, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(feature))
			return RemoveProvidedFromRaw(value);
		return false;
	}

	/// <inheritdoc/>
        protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
	{
		if (base.AddInternal(link, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(link))
		{
			AddProvidedFrom(PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.AsNodes<Languages.PowerSource>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
	{
		if (base.InsertInternal(link, index, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(link))
		{
			InsertProvidedFrom(index, PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.AsNodes<Languages.PowerSource>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
	{
		if (base.RemoveInternal(link, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.EqualsIdentity(link))
		{
			RemoveProvidedFrom(PowerBudgetLanguageLanguage.Instance.PowerConsumer_providedFrom.AsNodes<Languages.PowerSource>(value));
			return true;
		}

		return false;
	}
}

[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerModule")]
public partial class PowerModule : ConceptInstanceBase, INamedWritable, IPartitionInstance<INode>
{
	private string? _name = null;
	private bool SetNameRaw(string? value)
	{
		if (value == _name)
			return false;
		_name = value;
		return true;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "UnsetFeatureException">If Name has not been set</exception>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        [LionCoreMetaPointer(Language = typeof(LionWeb.Core.VersionSpecific.V2023_1.BuiltInsLanguage_2023_1), Key = "LionCore-builtins-INamed-name")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
	public string Name { get => _name ?? throw new UnsetFeatureException(_builtIns.INamed_name); set => SetName(value); }

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public bool TryGetName([NotNullWhenAttribute(true)] out string? name)
	{
		name = _name;
		return name != null;
	}
/// <remarks>Required Property</remarks>
/// <exception cref="InvalidValueException">If set to null</exception>
 INamedWritable INamedWritable.SetName(string value) => SetName(value);
	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public PowerModule SetName(string value)
	{
		SetRequiredReferenceTypeProperty<string>(value, _builtIns.INamed_name, _name, SetNameRaw);
		return this;
	}

	private bool SetContentsRaw(List<IPowerModuleContent> nodes) => ExchangeChildrenRaw(nodes, WritableContents());
	private bool AddContentsRaw(IPowerModuleContent? value) => AddChildRaw(value, WritableContents());
	private bool InsertContentsRaw(int index, IPowerModuleContent? value) => InsertChildRaw(index, value, WritableContents());
	private bool RemoveContentsRaw(IPowerModuleContent? value) => RemoveChildRaw(value, _contents);
	private List<IPowerModuleContent>? _contents;
	private static readonly IReadOnlyList<IPowerModuleContent> _emptyContents = [];
	private IReadOnlyList<IPowerModuleContent> ReadOnlyContents() => _contents?.AsReadOnly() ?? _emptyContents;
	private List<IPowerModuleContent> WritableContents() => _contents ??= [];
	/// <remarks>Optional Multiple Containment</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerModule-contents")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Containment, Optional = true, Multiple = true)]
	public IReadOnlyList<IPowerModuleContent> Contents { get => ReadOnlyContents(); init => AddContents(value); }

	/// <remarks>Optional Multiple Containment</remarks>
        public bool TryGetContents([NotNullWhenAttribute(true)] out IReadOnlyList<IPowerModuleContent> contents)
	{
		contents = ReadOnlyContents();
		return contents.Count != 0;
	}

	/// <remarks>Optional Multiple Containment</remarks>
        public PowerModule AddContents(IEnumerable<IPowerModuleContent> nodes)
	{
		AddOptionalMultipleContainment<IPowerModuleContent>(nodes, PowerBudgetLanguageLanguage.Instance.PowerModule_contents, WritableContents(), AddContentsRaw);
		return this;
	}

	/// <remarks>Optional Multiple Containment</remarks>
        public PowerModule InsertContents(int index, IEnumerable<IPowerModuleContent> nodes)
	{
		InsertOptionalMultipleContainment<IPowerModuleContent>(index, nodes, PowerBudgetLanguageLanguage.Instance.PowerModule_contents, WritableContents(), InsertContentsRaw);
		return this;
	}

	/// <remarks>Optional Multiple Containment</remarks>
        public PowerModule RemoveContents(IEnumerable<IPowerModuleContent> nodes)
	{
		RemoveOptionalMultipleContainment<IPowerModuleContent>(nodes, PowerBudgetLanguageLanguage.Instance.PowerModule_contents, _contents, RemoveContentsRaw);
		return this;
	}

	public PowerModule(string id) : base(id)
	{
		_notificationProducer = new PartitionNotificationProducer(this);
	}

	/// <inheritdoc/>
        public override Concept GetConcept() => PowerBudgetLanguageLanguage.Instance.PowerModule;
	private readonly IPartitionNotificationProducer? _notificationProducer;
	IPartitionNotificationProducer? IPartitionInstance.GetNotificationProducer() => _notificationProducer;
	/// <inheritdoc/>
        public INotificationSender? GetNotificationSender() => _notificationProducer;
	/// <inheritdoc/>
        protected override bool GetInternal(Feature? feature, out object? result)
	{
		if (base.GetInternal(feature, out result))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			result = Name;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(feature))
		{
			result = Contents;
			return true;
		}

		return false;
	}

	protected override bool TryGetPropertyRaw(Property feature, out object? result)
	{
		if (base.TryGetPropertyRaw(feature, out result))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			result = _name;
			return true;
		}

		return false;
	}

	protected override bool TryGetContainmentsRaw(Containment feature, out IReadOnlyList<IReadableNode> result)
	{
		if (base.TryGetContainmentsRaw(feature, out result))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(feature))
		{
			result = ReadOnlyContents();
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool SetInternal(Feature? feature, object? value)
	{
		if (base.SetInternal(feature, value))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			if (value is string v)
			{
				SetName(v);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(feature))
		{
			SetOptionalMultipleContainment<IPowerModuleContent>(value, PowerBudgetLanguageLanguage.Instance.PowerModule_contents, WritableContents(), SetContentsRaw);
			return true;
		}

		return false;
	}

	protected override bool SetPropertyRaw(Property feature, object? value)
	{
		if (base.SetPropertyRaw(feature, value))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature) && value is null or string)
			return SetNameRaw((string?)value);
		return false;
	}

	/// <inheritdoc/>
        public override IEnumerable<Feature> CollectAllSetFeatures()
	{
		List<Feature> result = base.CollectAllSetFeatures().ToList();
		if (TryGetName(out _))
			result.Add(_builtIns.INamed_name);
		if (TryGetContents(out _))
			result.Add(PowerBudgetLanguageLanguage.Instance.PowerModule_contents);
		return result;
	}

	protected override bool AddContainmentsRaw(Containment feature, IWritableNode value)
	{
		if (base.AddContainmentsRaw(feature, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(feature) && value is Languages.IPowerModuleContent v0)
			return AddContentsRaw(v0);
		return false;
	}

	protected override bool InsertContainmentsRaw(Containment feature, int index, IWritableNode value)
	{
		if (base.InsertContainmentsRaw(feature, index, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(feature) && value is Languages.IPowerModuleContent v0)
			return InsertContentsRaw(index, v0);
		return false;
	}

	protected override bool RemoveContainmentsRaw(Containment feature, IWritableNode value)
	{
		if (base.RemoveContainmentsRaw(feature, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(feature) && value is Languages.IPowerModuleContent v0)
			return RemoveContentsRaw(v0);
		return false;
	}

	/// <inheritdoc/>
        protected override bool AddInternal(Link? link, IEnumerable<IReadableNode> value)
	{
		if (base.AddInternal(link, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(link))
		{
			AddContents(PowerBudgetLanguageLanguage.Instance.PowerModule_contents.AsNodes<Languages.IPowerModuleContent>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool InsertInternal(Link? link, int index, IEnumerable<IReadableNode> value)
	{
		if (base.InsertInternal(link, index, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(link))
		{
			InsertContents(index, PowerBudgetLanguageLanguage.Instance.PowerModule_contents.AsNodes<Languages.IPowerModuleContent>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool RemoveInternal(Link? link, IEnumerable<IReadableNode> value)
	{
		if (base.RemoveInternal(link, value))
			return true;
		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(link))
		{
			RemoveContents(PowerBudgetLanguageLanguage.Instance.PowerModule_contents.AsNodes<Languages.IPowerModuleContent>(value));
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool DetachChild(INode child, bool notify)
	{
		if (base.DetachChild(child, notify))
			return true;
		Containment? c = GetContainmentOf(child);
		if (PowerBudgetLanguageLanguage.Instance.PowerModule_contents.EqualsIdentity(c))
		{
			RemoveSelfParent((IPowerModuleContent)child, WritableContents(), PowerBudgetLanguageLanguage.Instance.PowerModule_contents, null, notify ? ContainmentRemover<IPowerModuleContent>(PowerBudgetLanguageLanguage.Instance.PowerModule_contents) : null);
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        public override Containment? GetContainmentOf(INode child)
	{
		Containment? result = base.GetContainmentOf(child);
		if (result != null)
			return result;
		if (child is IPowerModuleContent child0 && (_contents?.Contains(child0) ?? false))
			return PowerBudgetLanguageLanguage.Instance.PowerModule_contents;
		return null;
	}
}

[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerSource")]
public partial class PowerSource : ConceptInstanceBase, IPowerModuleContent, IPowerParticipant, INamedWritable
{
	private string? _name = null;
	private bool SetNameRaw(string? value)
	{
		if (value == _name)
			return false;
		_name = value;
		return true;
	}

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "UnsetFeatureException">If Name has not been set</exception>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        [LionCoreMetaPointer(Language = typeof(LionWeb.Core.VersionSpecific.V2023_1.BuiltInsLanguage_2023_1), Key = "LionCore-builtins-INamed-name")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = false, Multiple = false)]
	public string Name { get => _name ?? throw new UnsetFeatureException(_builtIns.INamed_name); set => SetName(value); }

	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public bool TryGetName([NotNullWhenAttribute(true)] out string? name)
	{
		name = _name;
		return name != null;
	}
/// <remarks>Required Property</remarks>
/// <exception cref="InvalidValueException">If set to null</exception>
 INamedWritable INamedWritable.SetName(string value) => SetName(value);
	/// <remarks>Required Property</remarks>
    	/// <exception cref = "InvalidValueException">If set to null</exception>
        public PowerSource SetName(string value)
	{
		SetRequiredReferenceTypeProperty<string>(value, _builtIns.INamed_name, _name, SetNameRaw);
		return this;
	}

	private int? _continuous = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "IPowerParticipant-continuous")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public int? Continuous { get => _continuous; set => SetContinuous(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetContinuous([NotNullWhenAttribute(true)] out int? continuous)
	{
		continuous = _continuous;
		return continuous != null;
	}

	private bool SetContinuousRaw(int? value)
	{
		if (value == _continuous)
			return false;
		_continuous = value;
		return true;
	}
/// <remarks>Optional Property</remarks>
 IPowerParticipant IPowerParticipant.SetContinuous(int? value) => SetContinuous(value);
	/// <remarks>Optional Property</remarks>
        public PowerSource SetContinuous(int? value)
	{
		SetOptionalValueTypeProperty<int>(value, PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous, _continuous, SetContinuousRaw);
		return this;
	}

	private int? _peak = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "IPowerParticipant-peak")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public int? Peak { get => _peak; set => SetPeak(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetPeak([NotNullWhenAttribute(true)] out int? peak)
	{
		peak = _peak;
		return peak != null;
	}

	private bool SetPeakRaw(int? value)
	{
		if (value == _peak)
			return false;
		_peak = value;
		return true;
	}
/// <remarks>Optional Property</remarks>
 IPowerParticipant IPowerParticipant.SetPeak(int? value) => SetPeak(value);
	/// <remarks>Optional Property</remarks>
        public PowerSource SetPeak(int? value)
	{
		SetOptionalValueTypeProperty<int>(value, PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak, _peak, SetPeakRaw);
		return this;
	}

	private PowerSourceKind? _kind = null;
	/// <remarks>Optional Property</remarks>
        [LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerSource-kind")]
	[LionCoreFeature(Kind = LionCoreFeatureKind.Property, Optional = true, Multiple = false)]
	public PowerSourceKind? Kind { get => _kind; set => SetKind(value); }

	/// <remarks>Optional Property</remarks>
        public bool TryGetKind([NotNullWhenAttribute(true)] out PowerSourceKind? kind)
	{
		kind = _kind;
		return kind != null;
	}

	private bool SetKindRaw(PowerSourceKind? value)
	{
		if (value == _kind)
			return false;
		_kind = value;
		return true;
	}

	/// <remarks>Optional Property</remarks>
        public PowerSource SetKind(PowerSourceKind? value)
	{
		SetOptionalValueTypeProperty<PowerSourceKind>(value, PowerBudgetLanguageLanguage.Instance.PowerSource_kind, _kind, SetKindRaw);
		return this;
	}

	public PowerSource(string id) : base(id)
	{
	}

	/// <inheritdoc/>
        public override Concept GetConcept() => PowerBudgetLanguageLanguage.Instance.PowerSource;
	/// <inheritdoc/>
        protected override bool GetInternal(Feature? feature, out object? result)
	{
		if (base.GetInternal(feature, out result))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			result = Name;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous.EqualsIdentity(feature))
		{
			result = Continuous;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak.EqualsIdentity(feature))
		{
			result = Peak;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.PowerSource_kind.EqualsIdentity(feature))
		{
			result = Kind;
			return true;
		}

		return false;
	}

	protected override bool TryGetPropertyRaw(Property feature, out object? result)
	{
		if (base.TryGetPropertyRaw(feature, out result))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			result = _name;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous.EqualsIdentity(feature))
		{
			result = _continuous;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak.EqualsIdentity(feature))
		{
			result = _peak;
			return true;
		}

		if (PowerBudgetLanguageLanguage.Instance.PowerSource_kind.EqualsIdentity(feature))
		{
			result = _kind;
			return true;
		}

		return false;
	}

	/// <inheritdoc/>
        protected override bool SetInternal(Feature? feature, object? value)
	{
		if (base.SetInternal(feature, value))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature))
		{
			if (value is string v)
			{
				SetName(v);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous.EqualsIdentity(feature))
		{
			if (value is null or int)
			{
				SetContinuous((int?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak.EqualsIdentity(feature))
		{
			if (value is null or int)
			{
				SetPeak((int?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		if (PowerBudgetLanguageLanguage.Instance.PowerSource_kind.EqualsIdentity(feature))
		{
			if (value is null or Languages.PowerSourceKind)
			{
				SetKind((Languages.PowerSourceKind?)value);
				return true;
			}

			throw new InvalidValueException(feature, value);
		}

		return false;
	}

	protected override bool SetPropertyRaw(Property feature, object? value)
	{
		if (base.SetPropertyRaw(feature, value))
			return true;
		if (_builtIns.INamed_name.EqualsIdentity(feature) && value is null or string)
			return SetNameRaw((string?)value);
		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous.EqualsIdentity(feature) && value is null or int)
			return SetContinuousRaw((int?)value);
		if (PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak.EqualsIdentity(feature) && value is null or int)
			return SetPeakRaw((int?)value);
		if (PowerBudgetLanguageLanguage.Instance.PowerSource_kind.EqualsIdentity(feature) && value is null or Languages.PowerSourceKind)
			return SetKindRaw((Languages.PowerSourceKind?)value);
		return false;
	}

	/// <inheritdoc/>
        public override IEnumerable<Feature> CollectAllSetFeatures()
	{
		List<Feature> result = base.CollectAllSetFeatures().ToList();
		if (TryGetName(out _))
			result.Add(_builtIns.INamed_name);
		if (TryGetContinuous(out _))
			result.Add(PowerBudgetLanguageLanguage.Instance.IPowerParticipant_continuous);
		if (TryGetPeak(out _))
			result.Add(PowerBudgetLanguageLanguage.Instance.IPowerParticipant_peak);
		if (TryGetKind(out _))
			result.Add(PowerBudgetLanguageLanguage.Instance.PowerSource_kind);
		return result;
	}
}

[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerSourceKind")]
public enum PowerSourceKind
{
	[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerSourceKind-diesel")]
	diesel,
	[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerSourceKind-nuclear")]
	nuclear,
	[LionCoreMetaPointer(Language = typeof(PowerBudgetLanguageLanguage), Key = "PowerSourceKind-solar")]
	solar
}